name: CI

on:
  push:
    branches: [ main, "*.x" ]
  pull_request:
    branches: [ main, "*.x" ]

permissions:
  contents: read

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            php: "8.2"
            coverage: "none"
          - os: "ubuntu-latest"
            php: "8.3"
            coverage: "none"
          - os: "ubuntu-latest"
            php: "8.4"
            coverage: "pcov"
          - os: "ubuntu-latest"
            php: "8.5"
            coverage: "none"

    steps:
      - uses: actions/checkout@v6

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # Only report coverage once
          coverage: ${{ matrix.coverage }}

      - name: Validate composer.json
        run: composer validate --strict --no-check-lock

      - name: Install dependencies
        run: composer -n update --prefer-dist -o

      - name: Security audit
        run: composer audit

      - name: Run test suite
        if: matrix.coverage == 'none'
        run: composer run-script test

      - name: Run coverage
        if: matrix.coverage == 'pcov'
        run: composer run-script coverage

      - name: Upload coverage results to Coveralls
        if: matrix.coverage == 'pcov'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: composer run-script coveralls
